require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollabsController do

  # This should return the minimal set of attributes required to create a valid
  # Collab. As you add validations to Collab, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollabsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all collabs as @collabs" do
      collab = Collab.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:collabs)).to eq([collab])
    end
  end

  describe "GET show" do
    it "assigns the requested collab as @collab" do
      collab = Collab.create! valid_attributes
      get :show, {:id => collab.to_param}, valid_session
      expect(assigns(:collab)).to eq(collab)
    end
  end

  describe "GET new" do
    it "assigns a new collab as @collab" do
      get :new, {}, valid_session
      expect(assigns(:collab)).to be_a_new(Collab)
    end
  end

  describe "GET edit" do
    it "assigns the requested collab as @collab" do
      collab = Collab.create! valid_attributes
      get :edit, {:id => collab.to_param}, valid_session
      expect(assigns(:collab)).to eq(collab)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Collab" do
        expect {
          post :create, {:collab => valid_attributes}, valid_session
        }.to change(Collab, :count).by(1)
      end

      it "assigns a newly created collab as @collab" do
        post :create, {:collab => valid_attributes}, valid_session
        expect(assigns(:collab)).to be_a(Collab)
        expect(assigns(:collab)).to be_persisted
      end

      it "redirects to the created collab" do
        post :create, {:collab => valid_attributes}, valid_session
        expect(response).to redirect_to(Collab.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collab as @collab" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Collab).to receive(:save).and_return(false)
        post :create, {:collab => { "email" => "invalid value" }}, valid_session
        expect(assigns(:collab)).to be_a_new(Collab)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Collab).to receive(:save).and_return(false)
        post :create, {:collab => { "email" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested collab" do
        collab = Collab.create! valid_attributes
        # Assuming there are no other collabs in the database, this
        # specifies that the Collab created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Collab).to receive(:update).with({ "email" => "MyString" })
        put :update, {:id => collab.to_param, :collab => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested collab as @collab" do
        collab = Collab.create! valid_attributes
        put :update, {:id => collab.to_param, :collab => valid_attributes}, valid_session
        expect(assigns(:collab)).to eq(collab)
      end

      it "redirects to the collab" do
        collab = Collab.create! valid_attributes
        put :update, {:id => collab.to_param, :collab => valid_attributes}, valid_session
        expect(response).to redirect_to(collab)
      end
    end

    describe "with invalid params" do
      it "assigns the collab as @collab" do
        collab = Collab.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Collab).to receive(:save).and_return(false)
        put :update, {:id => collab.to_param, :collab => { "email" => "invalid value" }}, valid_session
        expect(assigns(:collab)).to eq(collab)
      end

      it "re-renders the 'edit' template" do
        collab = Collab.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Collab).to receive(:save).and_return(false)
        put :update, {:id => collab.to_param, :collab => { "email" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested collab" do
      collab = Collab.create! valid_attributes
      expect {
        delete :destroy, {:id => collab.to_param}, valid_session
      }.to change(Collab, :count).by(-1)
    end

    it "redirects to the collabs list" do
      collab = Collab.create! valid_attributes
      delete :destroy, {:id => collab.to_param}, valid_session
      expect(response).to redirect_to(collabs_url)
    end
  end

end
